/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product; 

/**
 *
 * @author deshna
 */
public class Doctor extends javax.swing.JPanel {

    /**
     * Creates new form Doctor
     */
    
    Product product;
            
    public Doctor(Product product) {
        initComponents();
        this.product=product;     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameJTextField1 = new javax.swing.JTextField();
        docAddressJTextField2 = new javax.swing.JTextField();
        docIdTextField3 = new javax.swing.JTextField();
        specialityJTextField = new javax.swing.JTextField();
        personJLbl = new javax.swing.JLabel();
        NameJLbl = new javax.swing.JLabel();
        SsnJLbl = new javax.swing.JLabel();
        WebsiteUrlJLbl = new javax.swing.JLabel();
        emailIdJLbl = new javax.swing.JLabel();
        emailIdJLbl1 = new javax.swing.JLabel();
        availaibilityJTextField = new javax.swing.JTextField();
        emailIdJLbl2 = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        emailIdJLbl3 = new javax.swing.JLabel();
        branchJTextField = new javax.swing.JTextField();
        saveJButton1 = new javax.swing.JButton();

        docAddressJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docAddressJTextField2ActionPerformed(evt);
            }
        });

        specialityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityJTextFieldActionPerformed(evt);
            }
        });

        personJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl.setText("DOCTOR");

        NameJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameJLbl.setText("Name");

        SsnJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl.setText("Clinic Address");

        WebsiteUrlJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl.setText("ID");

        emailIdJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl.setText("Speciality");

        emailIdJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl1.setText("Availaibility");

        availaibilityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availaibilityJTextFieldActionPerformed(evt);
            }
        });

        emailIdJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl2.setText("Office Contact Number");

        numTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextFieldActionPerformed(evt);
            }
        });

        emailIdJLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl3.setText("Branch");

        branchJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchJTextFieldActionPerformed(evt);
            }
        });

        saveJButton1.setText("Save");
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(personJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailIdJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailIdJLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                            .addComponent(emailIdJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specialityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availaibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SsnJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(docAddressJTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(saveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docAddressJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SsnJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(personJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availaibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void docAddressJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docAddressJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docAddressJTextField2ActionPerformed

    private void specialityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityJTextFieldActionPerformed

    private void availaibilityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availaibilityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availaibilityJTextFieldActionPerformed

    private void numTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextFieldActionPerformed

    private void branchJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchJTextFieldActionPerformed

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed
        // TODO add your handling code here:
        
        product.setDocName(nameJTextField1.getText());
        product.setBranch(branchJTextField.getText());
        product.setOfficeContact(numTextField.getText());
        product.setAvailaibility(availaibilityJTextField.getText());
        product.setSpeciality(specialityJTextField.getText());
        product.setDocId(docIdTextField3.getText());
        product.setDocAddress(docAddressJTextField2.getText());
       
        
        JOptionPane.showMessageDialog(this, "Person Details Saved");
    }//GEN-LAST:event_saveJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameJLbl;
    private javax.swing.JLabel SsnJLbl;
    private javax.swing.JLabel WebsiteUrlJLbl;
    private javax.swing.JTextField availaibilityJTextField;
    private javax.swing.JTextField branchJTextField;
    private javax.swing.JTextField docAddressJTextField2;
    private javax.swing.JTextField docIdTextField3;
    private javax.swing.JLabel emailIdJLbl;
    private javax.swing.JLabel emailIdJLbl1;
    private javax.swing.JLabel emailIdJLbl2;
    private javax.swing.JLabel emailIdJLbl3;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTextField numTextField;
    private javax.swing.JLabel personJLbl;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JTextField specialityJTextField;
    // End of variables declaration//GEN-END:variables
}
