/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Product;

/**
 *
 * @author deshna
 */
public class Driver extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    
    Product product;
            
    public Driver(Product product) {
        initComponents();
        this.product=product;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DriverJSplitPane3 = new javax.swing.JSplitPane();
        driverLeftJPanel1 = new javax.swing.JPanel();
        driverJLabel1 = new javax.swing.JLabel();
        driverRightJPanel2 = new javax.swing.JPanel();
        LicenseJLabel2 = new javax.swing.JLabel();
        licenseJTextField1 = new javax.swing.JTextField();
        SaveJButton = new javax.swing.JButton();

        driverJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        driverJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverJLabel1.setText("Driver");

        javax.swing.GroupLayout driverLeftJPanel1Layout = new javax.swing.GroupLayout(driverLeftJPanel1);
        driverLeftJPanel1.setLayout(driverLeftJPanel1Layout);
        driverLeftJPanel1Layout.setHorizontalGroup(
            driverLeftJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLeftJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );
        driverLeftJPanel1Layout.setVerticalGroup(
            driverLeftJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverLeftJPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(driverJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        DriverJSplitPane3.setLeftComponent(driverLeftJPanel1);

        LicenseJLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LicenseJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LicenseJLabel2.setText("License");

        licenseJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        licenseJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseJTextField1ActionPerformed(evt);
            }
        });

        SaveJButton.setText("Save");
        SaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverRightJPanel2Layout = new javax.swing.GroupLayout(driverRightJPanel2);
        driverRightJPanel2.setLayout(driverRightJPanel2Layout);
        driverRightJPanel2Layout.setHorizontalGroup(
            driverRightJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverRightJPanel2Layout.createSequentialGroup()
                .addGroup(driverRightJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(driverRightJPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LicenseJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(licenseJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(driverRightJPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        driverRightJPanel2Layout.setVerticalGroup(
            driverRightJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverRightJPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(driverRightJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(SaveJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        DriverJSplitPane3.setRightComponent(driverRightJPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DriverJSplitPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DriverJSplitPane3)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void licenseJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseJTextField1ActionPerformed

    private void SaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveJButtonActionPerformed
        // TODO add your handling code here:
        product.setModel(licenseJTextField1.getText());
    }//GEN-LAST:event_SaveJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane DriverJSplitPane3;
    private javax.swing.JLabel LicenseJLabel2;
    private javax.swing.JButton SaveJButton;
    private javax.swing.JLabel driverJLabel1;
    private javax.swing.JPanel driverLeftJPanel1;
    private javax.swing.JPanel driverRightJPanel2;
    private javax.swing.JTextField licenseJTextField1;
    // End of variables declaration//GEN-END:variables
}
