/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import model.Product;
/**
 *
 * @author deshna
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    Product product;
    
    public mainJFrame() {
        initComponents();
        product = new Product();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PersonJBt = new javax.swing.JButton();
        addressJBt = new javax.swing.JButton();
        driverJBt = new javax.swing.JButton();
        vehiclaRegiBt = new javax.swing.JButton();
        patientsJBt = new javax.swing.JButton();
        doctorJBt = new javax.swing.JButton();
        insuranceJBt = new javax.swing.JButton();
        reportJBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        PersonJBt.setText("Person");
        PersonJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonJBtActionPerformed(evt);
            }
        });

        addressJBt.setText("Address");
        addressJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJBtActionPerformed(evt);
            }
        });

        driverJBt.setText("Driver");
        driverJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverJBtActionPerformed(evt);
            }
        });

        vehiclaRegiBt.setText("Vehical Regisration ");
        vehiclaRegiBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclaRegiBtActionPerformed(evt);
            }
        });

        patientsJBt.setText("Patients");
        patientsJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsJBtActionPerformed(evt);
            }
        });

        doctorJBt.setText("Doctor");
        doctorJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorJBtActionPerformed(evt);
            }
        });

        insuranceJBt.setText("Insurance ");
        insuranceJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceJBtActionPerformed(evt);
            }
        });

        reportJBt.setText("Patient Report");
        reportJBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportJBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceJBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorJBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientsJBt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vehiclaRegiBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PersonJBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressJBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(driverJBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PersonJBt)
                .addGap(18, 18, 18)
                .addComponent(addressJBt)
                .addGap(18, 18, 18)
                .addComponent(driverJBt)
                .addGap(18, 18, 18)
                .addComponent(vehiclaRegiBt)
                .addGap(18, 18, 18)
                .addComponent(patientsJBt)
                .addGap(18, 18, 18)
                .addComponent(doctorJBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insuranceJBt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportJBt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonJBtActionPerformed
        // TODO add your handling code here:
        Person personPanel = new Person(product);
        jSplitPane1.setRightComponent(personPanel);
    }//GEN-LAST:event_PersonJBtActionPerformed

    private void addressJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJBtActionPerformed
        // TODO add your handling code here:
        Address address = new Address(product);
        jSplitPane1.setRightComponent(address);
    }//GEN-LAST:event_addressJBtActionPerformed

    private void driverJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverJBtActionPerformed
        // TODO add your handling code here:
        Driver driver = new Driver(product);
        jSplitPane1.setRightComponent(driver);
    }//GEN-LAST:event_driverJBtActionPerformed

    private void vehiclaRegiBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclaRegiBtActionPerformed
        // TODO add your handling code here:
        VehicalRegistration vehicalRegi = new VehicalRegistration(product);
        jSplitPane1.setRightComponent(vehicalRegi);
    }//GEN-LAST:event_vehiclaRegiBtActionPerformed

    private void patientsJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsJBtActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient(product);
        jSplitPane1.setRightComponent(patient);
    }//GEN-LAST:event_patientsJBtActionPerformed

    private void reportJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJBtActionPerformed
        // TODO add your handling code here:
        Report report = new Report(product);
        jSplitPane1.setRightComponent(report);

    }//GEN-LAST:event_reportJBtActionPerformed

    private void insuranceJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceJBtActionPerformed
        // TODO add your handling code here:
        Insurance insurance = new Insurance(product);
        jSplitPane1.setRightComponent(insurance);
        
    }//GEN-LAST:event_insuranceJBtActionPerformed

    private void doctorJBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorJBtActionPerformed
        // TODO add your handling code here:
        Doctor doctor = new Doctor(product);
        jSplitPane1.setRightComponent(doctor);
        
    }//GEN-LAST:event_doctorJBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PersonJBt;
    private javax.swing.JButton addressJBt;
    private javax.swing.JButton doctorJBt;
    private javax.swing.JButton driverJBt;
    private javax.swing.JButton insuranceJBt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton patientsJBt;
    private javax.swing.JButton reportJBt;
    private javax.swing.JButton vehiclaRegiBt;
    // End of variables declaration//GEN-END:variables
}
