/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Product; 

/**
 *
 * @author deshna
 */
public class Person extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    Product product;
    
    public Person(Product product) {
        initComponents();
        this.product=product;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        personJLbl = new javax.swing.JLabel();
        NameJLbl = new javax.swing.JLabel();
        SsnJLbl = new javax.swing.JLabel();
        WebsiteUrlJLbl = new javax.swing.JLabel();
        emailIdJLbl = new javax.swing.JLabel();
        bloodGrpJLbl = new javax.swing.JLabel();
        contactNumJLbl = new javax.swing.JLabel();
        occupationJLbl = new javax.swing.JLabel();
        ageJLbl = new javax.swing.JLabel();
        genderJLbl = new javax.swing.JLabel();
        DiseaseNameJLbl = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();
        ssnJTextField2 = new javax.swing.JTextField();
        WebsiteUrlJTextField3 = new javax.swing.JTextField();
        emailIdJTextField4 = new javax.swing.JTextField();
        bloodGroupJTextField5 = new javax.swing.JTextField();
        contactNumJTextField6 = new javax.swing.JTextField();
        occupationJTextField7 = new javax.swing.JTextField();
        ageJTextField = new javax.swing.JTextField();
        genderJTextField9 = new javax.swing.JTextField();
        DiseaseNameJTextField10 = new javax.swing.JTextField();
        saveJButton1 = new javax.swing.JButton();

        personJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl.setText("PERSON");

        NameJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameJLbl.setText("Name");

        SsnJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl.setText("SSN");

        WebsiteUrlJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl.setText("Website URL");

        emailIdJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl.setText("Email Id ");

        bloodGrpJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodGrpJLbl.setText("Blood Group");

        contactNumJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNumJLbl.setText("Contact Number");

        occupationJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupationJLbl.setText("Occupation");

        ageJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageJLbl.setText("Age");

        genderJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderJLbl.setText("Gender");

        DiseaseNameJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiseaseNameJLbl.setText("Disease Name");

        ssnJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnJTextField2ActionPerformed(evt);
            }
        });

        emailIdJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdJTextField4ActionPerformed(evt);
            }
        });

        bloodGroupJTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupJTextField5ActionPerformed(evt);
            }
        });

        genderJTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTextField9ActionPerformed(evt);
            }
        });

        DiseaseNameJTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseNameJTextField10ActionPerformed(evt);
            }
        });

        saveJButton1.setText("Save");
        saveJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(NameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(SsnJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ssnJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WebsiteUrlJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(emailIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailIdJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(personJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bloodGrpJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bloodGroupJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(occupationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiseaseNameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactNumJTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(occupationJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderJTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiseaseNameJTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(saveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssnJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SsnJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WebsiteUrlJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailIdJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGroupJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGrpJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumJTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occupationJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(occupationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderJTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiseaseNameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DiseaseNameJTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(saveJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DiseaseNameJTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseNameJTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiseaseNameJTextField10ActionPerformed

    private void genderJTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTextField9ActionPerformed

    private void bloodGroupJTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupJTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupJTextField5ActionPerformed

    private void emailIdJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdJTextField4ActionPerformed

    private void ssnJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnJTextField2ActionPerformed

    private void saveJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButton1ActionPerformed
        // TODO add your handling code here:
        product.setName(nameJTextField1.getText());
        product.setAge(ageJTextField.getText());
        product.setEmailId(emailIdJTextField4.getText());
        product.setGender(genderJTextField9.getText());
        product.setSSN(ssnJTextField2.getText());
        product.setWebsiteUrl(WebsiteUrlJTextField3.getText());
        product.setContactNum(contactNumJTextField6.getText());
        product.setOccupation(occupationJTextField7.getText());
        product.setDiseaseName(DiseaseNameJTextField10.getText());
        
        
        JOptionPane.showMessageDialog(this, "Person Details Saved");
    }//GEN-LAST:event_saveJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiseaseNameJLbl;
    private javax.swing.JTextField DiseaseNameJTextField10;
    private javax.swing.JLabel NameJLbl;
    private javax.swing.JLabel SsnJLbl;
    private javax.swing.JLabel WebsiteUrlJLbl;
    private javax.swing.JTextField WebsiteUrlJTextField3;
    private javax.swing.JLabel ageJLbl;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JTextField bloodGroupJTextField5;
    private javax.swing.JLabel bloodGrpJLbl;
    private javax.swing.JLabel contactNumJLbl;
    private javax.swing.JTextField contactNumJTextField6;
    private javax.swing.JLabel emailIdJLbl;
    private javax.swing.JTextField emailIdJTextField4;
    private javax.swing.JLabel genderJLbl;
    private javax.swing.JTextField genderJTextField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JLabel occupationJLbl;
    private javax.swing.JTextField occupationJTextField7;
    private javax.swing.JLabel personJLbl;
    private javax.swing.JButton saveJButton1;
    private javax.swing.JTextField ssnJTextField2;
    // End of variables declaration//GEN-END:variables
}
