/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.Product; 

/**
 *
 * @author deshna
 */
public class Report extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    Product product;
    public Report(Product product) {
        initComponents();
        this.product=product;
        displayProduct(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageJTextField = new javax.swing.JTextField();
        ageJLbl = new javax.swing.JLabel();
        genderJTextField9 = new javax.swing.JTextField();
        genderJLbl = new javax.swing.JLabel();
        DiseaseNameJTextField10 = new javax.swing.JTextField();
        DiseaseNameJLbl = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();
        NameJLbl = new javax.swing.JLabel();
        ssnJTextField2 = new javax.swing.JTextField();
        SsnJLbl = new javax.swing.JLabel();
        WebsiteUrlJTextField3 = new javax.swing.JTextField();
        WebsiteUrlJLbl = new javax.swing.JLabel();
        emailIdJTextField4 = new javax.swing.JTextField();
        emailIdJLbl = new javax.swing.JLabel();
        bloodGroupJTextField5 = new javax.swing.JTextField();
        bloodGrpJLbl = new javax.swing.JLabel();
        contactNumJTextField6 = new javax.swing.JTextField();
        contactNumJLbl = new javax.swing.JLabel();
        occupationJTextField7 = new javax.swing.JTextField();
        occupationJLbl = new javax.swing.JLabel();
        SsnJLbl1 = new javax.swing.JLabel();
        WebsiteUrlJLbl1 = new javax.swing.JLabel();
        emailIdJLbl1 = new javax.swing.JLabel();
        modelJTextField1 = new javax.swing.JTextField();
        colorJTextField = new javax.swing.JTextField();
        brandJTextField3 = new javax.swing.JTextField();
        serialNumJTextField4 = new javax.swing.JTextField();
        NameJLbl1 = new javax.swing.JLabel();
        addRightJPanel = new javax.swing.JPanel();
        cityJLbl = new javax.swing.JLabel();
        stateJLbl = new javax.swing.JLabel();
        countryJLbl = new javax.swing.JLabel();
        insuranceIdTxtField = new javax.swing.JTextField();
        cityJTxtField = new javax.swing.JTextField();
        deductableJTxtField = new javax.swing.JTextField();
        textStatementTxtField = new javax.swing.JTextField();
        gpsLocationJLbl = new javax.swing.JLabel();
        personJLbl1 = new javax.swing.JLabel();
        personJLbl = new javax.swing.JLabel();
        addRightJPanel1 = new javax.swing.JPanel();
        gpsLocationJLbl1 = new javax.swing.JLabel();
        cityJLbl1 = new javax.swing.JLabel();
        stateJLbl1 = new javax.swing.JLabel();
        countryJLbl1 = new javax.swing.JLabel();
        pincodeJLbl = new javax.swing.JLabel();
        gpsLocationTxtField = new javax.swing.JTextField();
        cityJTxtField1 = new javax.swing.JTextField();
        stateJTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        pincodeTxtField = new javax.swing.JTextField();
        personJLbl3 = new javax.swing.JLabel();
        docIdTextField3 = new javax.swing.JTextField();
        emailIdJLbl3 = new javax.swing.JLabel();
        specialityJTextField = new javax.swing.JTextField();
        branchJTextField = new javax.swing.JTextField();
        NameJLbl2 = new javax.swing.JLabel();
        SsnJLbl2 = new javax.swing.JLabel();
        WebsiteUrlJLbl2 = new javax.swing.JLabel();
        emailIdJLbl2 = new javax.swing.JLabel();
        emailIdJLbl4 = new javax.swing.JLabel();
        availaibilityJTextField = new javax.swing.JTextField();
        emailIdJLbl5 = new javax.swing.JLabel();
        numTextField = new javax.swing.JTextField();
        nameJTextField2 = new javax.swing.JTextField();
        docAddressJTextField2 = new javax.swing.JTextField();
        personJLbl4 = new javax.swing.JLabel();
        LicenseJLabel2 = new javax.swing.JLabel();
        licenseJTextField1 = new javax.swing.JTextField();
        personJLbl5 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        SsnJLbl3 = new javax.swing.JLabel();
        WebsiteUrlJLbl3 = new javax.swing.JLabel();
        emailIdJLbl6 = new javax.swing.JLabel();
        bloodGrpJLbl1 = new javax.swing.JLabel();
        contactNumJLbl1 = new javax.swing.JLabel();
        patientJTextField1 = new javax.swing.JTextField();
        lastDateJTextField2 = new javax.swing.JTextField();
        nxtAppJTextField3 = new javax.swing.JTextField();
        allergyJTextField4 = new javax.swing.JTextField();
        contactNumJTextField7 = new javax.swing.JTextField();
        personJLbl6 = new javax.swing.JLabel();
        personJLbl2 = new javax.swing.JLabel();
        medicationJTextField5 = new javax.swing.JTextField();

        ageJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageJLbl.setText("Age");

        genderJTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderJTextField9ActionPerformed(evt);
            }
        });

        genderJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genderJLbl.setText("Gender");

        DiseaseNameJTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiseaseNameJTextField10ActionPerformed(evt);
            }
        });

        DiseaseNameJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiseaseNameJLbl.setText("Disease Name");

        nameJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextField1ActionPerformed(evt);
            }
        });

        NameJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameJLbl.setText("Name");

        ssnJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnJTextField2ActionPerformed(evt);
            }
        });

        SsnJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl.setText("SSN");

        WebsiteUrlJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl.setText("Website URL");

        emailIdJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdJTextField4ActionPerformed(evt);
            }
        });

        emailIdJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl.setText("Email Id ");

        bloodGroupJTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupJTextField5ActionPerformed(evt);
            }
        });

        bloodGrpJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodGrpJLbl.setText("Blood Group");

        contactNumJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNumJLbl.setText("Contact Number");

        occupationJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        occupationJLbl.setText("Occupation");

        SsnJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl1.setText("Color ");

        WebsiteUrlJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl1.setText("Brand");

        emailIdJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl1.setText("Serial Number");

        colorJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJTextFieldActionPerformed(evt);
            }
        });

        brandJTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandJTextField3ActionPerformed(evt);
            }
        });

        serialNumJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumJTextField4ActionPerformed(evt);
            }
        });

        NameJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameJLbl1.setText("Model");

        cityJLbl.setText("Priminum");

        stateJLbl.setText("Deductable");

        countryJLbl.setText("Text Statement");

        insuranceIdTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceIdTxtFieldActionPerformed(evt);
            }
        });

        deductableJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deductableJTxtFieldActionPerformed(evt);
            }
        });

        gpsLocationJLbl.setText("Insurance ID");

        javax.swing.GroupLayout addRightJPanelLayout = new javax.swing.GroupLayout(addRightJPanel);
        addRightJPanel.setLayout(addRightJPanelLayout);
        addRightJPanelLayout.setHorizontalGroup(
            addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRightJPanelLayout.createSequentialGroup()
                .addGroup(addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addComponent(stateJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deductableJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addComponent(cityJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cityJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addComponent(gpsLocationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(insuranceIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addComponent(countryJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textStatementTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        addRightJPanelLayout.setVerticalGroup(
            addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRightJPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpsLocationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cityJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stateJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addRightJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(deductableJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textStatementTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        personJLbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl1.setText("VEHICAL REGISTRATION");

        personJLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl.setText("PATIENT REPORT");

        gpsLocationJLbl1.setText("GPS Location");

        cityJLbl1.setText("City ");

        stateJLbl1.setText("State");

        countryJLbl1.setText("Country");

        pincodeJLbl.setText("Pincode");

        gpsLocationTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpsLocationTxtFieldActionPerformed(evt);
            }
        });

        stateJTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJTxtFieldActionPerformed(evt);
            }
        });

        countryTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTxtFieldActionPerformed(evt);
            }
        });

        pincodeTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeTxtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRightJPanel1Layout = new javax.swing.GroupLayout(addRightJPanel1);
        addRightJPanel1.setLayout(addRightJPanel1Layout);
        addRightJPanel1Layout.setHorizontalGroup(
            addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRightJPanel1Layout.createSequentialGroup()
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addRightJPanel1Layout.createSequentialGroup()
                        .addComponent(stateJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(stateJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanel1Layout.createSequentialGroup()
                        .addComponent(cityJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(cityJTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanel1Layout.createSequentialGroup()
                        .addComponent(gpsLocationJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(gpsLocationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanel1Layout.createSequentialGroup()
                        .addComponent(countryJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addRightJPanel1Layout.createSequentialGroup()
                        .addComponent(pincodeJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(pincodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addRightJPanel1Layout.setVerticalGroup(
            addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRightJPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpsLocationJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpsLocationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityJTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateJTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addRightJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pincodeJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pincodeTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        personJLbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl3.setText("DRIVER");

        emailIdJLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl3.setText("Branch");

        specialityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialityJTextFieldActionPerformed(evt);
            }
        });

        branchJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchJTextFieldActionPerformed(evt);
            }
        });

        NameJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameJLbl2.setText("Name");

        SsnJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl2.setText("Clinic Address");

        WebsiteUrlJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl2.setText("ID");

        emailIdJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl2.setText("Speciality");

        emailIdJLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl4.setText("Availaibility");

        availaibilityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availaibilityJTextFieldActionPerformed(evt);
            }
        });

        emailIdJLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl5.setText("Office Contact Number");

        numTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTextFieldActionPerformed(evt);
            }
        });

        docAddressJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docAddressJTextField2ActionPerformed(evt);
            }
        });

        personJLbl4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl4.setText("ADDRESS");

        LicenseJLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LicenseJLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LicenseJLabel2.setText("License");

        licenseJTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        licenseJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseJTextField1ActionPerformed(evt);
            }
        });

        personJLbl5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl5.setText("DOCTOR");

        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtName.setText("Patient ID");

        SsnJLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SsnJLbl3.setText("Date of Last Visit");

        WebsiteUrlJLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WebsiteUrlJLbl3.setText("Next Appointment");

        emailIdJLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIdJLbl6.setText("Allergies");

        bloodGrpJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodGrpJLbl1.setText("On Medication");

        contactNumJLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contactNumJLbl1.setText("Primary Doctor");

        lastDateJTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDateJTextField2ActionPerformed(evt);
            }
        });

        allergyJTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergyJTextField4ActionPerformed(evt);
            }
        });

        personJLbl6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl6.setText("PATIENT");

        personJLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        personJLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personJLbl2.setText("INSURANCE");

        medicationJTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicationJTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(185, 185, 185)
                                            .addComponent(genderJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(contactNumJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(contactNumJTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(NameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12)
                                                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(DiseaseNameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(DiseaseNameJTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(bloodGrpJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(occupationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(WebsiteUrlJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(SsnJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ssnJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailIdJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bloodGroupJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(occupationJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(genderJTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NameJLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SsnJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modelJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(colorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(WebsiteUrlJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(serialNumJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(brandJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(52, 52, 52)
                            .addComponent(addRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(personJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(personJLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SsnJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WebsiteUrlJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdJLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdJLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailIdJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(docAddressJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(docIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(specialityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availaibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(LicenseJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(licenseJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personJLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(personJLbl1))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personJLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addRightJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(WebsiteUrlJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(personJLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bloodGrpJLbl1)
                                                .addComponent(emailIdJLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(contactNumJLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergyJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nxtAppJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(medicationJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SsnJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastDateJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(424, 424, 424))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(519, 519, 519)
                    .addComponent(NameJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(630, 630, 630)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(427, 427, 427)
                    .addComponent(personJLbl2)
                    .addContainerGap(729, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(personJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGrpJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGroupJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNumJTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderJTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(occupationJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(occupationJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiseaseNameJTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DiseaseNameJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contactNumJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WebsiteUrlJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WebsiteUrlJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SsnJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(personJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SsnJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brandJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WebsiteUrlJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(serialNumJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(addRightJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(personJLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personJLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SsnJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docAddressJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WebsiteUrlJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(docIdTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(specialityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdJLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availaibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailIdJLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicationJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGrpJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailIdJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contactNumJLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactNumJTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastDateJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SsnJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nxtAppJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WebsiteUrlJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allergyJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailIdJLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personJLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personJLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LicenseJLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(licenseJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addRightJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(491, 491, 491)
                    .addComponent(NameJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1116, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(345, 345, 345)
                    .addComponent(personJLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1265, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ssnJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnJTextField2ActionPerformed

    private void DiseaseNameJTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiseaseNameJTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiseaseNameJTextField10ActionPerformed

    private void bloodGroupJTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupJTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupJTextField5ActionPerformed

    private void genderJTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderJTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderJTextField9ActionPerformed

    private void emailIdJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdJTextField4ActionPerformed

    private void colorJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorJTextFieldActionPerformed

    private void brandJTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandJTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandJTextField3ActionPerformed

    private void serialNumJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumJTextField4ActionPerformed

    private void insuranceIdTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceIdTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceIdTxtFieldActionPerformed

    private void deductableJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deductableJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deductableJTxtFieldActionPerformed

    private void gpsLocationTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpsLocationTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpsLocationTxtFieldActionPerformed

    private void stateJTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJTxtFieldActionPerformed

    private void countryTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTxtFieldActionPerformed

    private void pincodeTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodeTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodeTxtFieldActionPerformed

    private void specialityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specialityJTextFieldActionPerformed

    private void branchJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchJTextFieldActionPerformed

    private void availaibilityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availaibilityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availaibilityJTextFieldActionPerformed

    private void numTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTextFieldActionPerformed

    private void docAddressJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docAddressJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docAddressJTextField2ActionPerformed

    private void licenseJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseJTextField1ActionPerformed

    private void lastDateJTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDateJTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastDateJTextField2ActionPerformed

    private void allergyJTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergyJTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergyJTextField4ActionPerformed

    private void nameJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextField1ActionPerformed

    private void medicationJTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicationJTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicationJTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiseaseNameJLbl;
    private javax.swing.JTextField DiseaseNameJTextField10;
    private javax.swing.JLabel LicenseJLabel2;
    private javax.swing.JLabel NameJLbl;
    private javax.swing.JLabel NameJLbl1;
    private javax.swing.JLabel NameJLbl2;
    private javax.swing.JLabel SsnJLbl;
    private javax.swing.JLabel SsnJLbl1;
    private javax.swing.JLabel SsnJLbl2;
    private javax.swing.JLabel SsnJLbl3;
    private javax.swing.JLabel WebsiteUrlJLbl;
    private javax.swing.JLabel WebsiteUrlJLbl1;
    private javax.swing.JLabel WebsiteUrlJLbl2;
    private javax.swing.JLabel WebsiteUrlJLbl3;
    private javax.swing.JTextField WebsiteUrlJTextField3;
    private javax.swing.JPanel addRightJPanel;
    private javax.swing.JPanel addRightJPanel1;
    private javax.swing.JLabel ageJLbl;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JTextField allergyJTextField4;
    private javax.swing.JTextField availaibilityJTextField;
    private javax.swing.JTextField bloodGroupJTextField5;
    private javax.swing.JLabel bloodGrpJLbl;
    private javax.swing.JLabel bloodGrpJLbl1;
    private javax.swing.JTextField branchJTextField;
    private javax.swing.JTextField brandJTextField3;
    private javax.swing.JLabel cityJLbl;
    private javax.swing.JLabel cityJLbl1;
    private javax.swing.JTextField cityJTxtField;
    private javax.swing.JTextField cityJTxtField1;
    private javax.swing.JTextField colorJTextField;
    private javax.swing.JLabel contactNumJLbl;
    private javax.swing.JLabel contactNumJLbl1;
    private javax.swing.JTextField contactNumJTextField6;
    private javax.swing.JTextField contactNumJTextField7;
    private javax.swing.JLabel countryJLbl;
    private javax.swing.JLabel countryJLbl1;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JTextField deductableJTxtField;
    private javax.swing.JTextField docAddressJTextField2;
    private javax.swing.JTextField docIdTextField3;
    private javax.swing.JLabel emailIdJLbl;
    private javax.swing.JLabel emailIdJLbl1;
    private javax.swing.JLabel emailIdJLbl2;
    private javax.swing.JLabel emailIdJLbl3;
    private javax.swing.JLabel emailIdJLbl4;
    private javax.swing.JLabel emailIdJLbl5;
    private javax.swing.JLabel emailIdJLbl6;
    private javax.swing.JTextField emailIdJTextField4;
    private javax.swing.JLabel genderJLbl;
    private javax.swing.JTextField genderJTextField9;
    private javax.swing.JLabel gpsLocationJLbl;
    private javax.swing.JLabel gpsLocationJLbl1;
    private javax.swing.JTextField gpsLocationTxtField;
    private javax.swing.JTextField insuranceIdTxtField;
    private javax.swing.JTextField lastDateJTextField2;
    private javax.swing.JTextField licenseJTextField1;
    private javax.swing.JTextField medicationJTextField5;
    private javax.swing.JTextField modelJTextField1;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTextField nameJTextField2;
    private javax.swing.JTextField numTextField;
    private javax.swing.JTextField nxtAppJTextField3;
    private javax.swing.JLabel occupationJLbl;
    private javax.swing.JTextField occupationJTextField7;
    private javax.swing.JTextField patientJTextField1;
    private javax.swing.JLabel personJLbl;
    private javax.swing.JLabel personJLbl1;
    private javax.swing.JLabel personJLbl2;
    private javax.swing.JLabel personJLbl3;
    private javax.swing.JLabel personJLbl4;
    private javax.swing.JLabel personJLbl5;
    private javax.swing.JLabel personJLbl6;
    private javax.swing.JLabel pincodeJLbl;
    private javax.swing.JTextField pincodeTxtField;
    private javax.swing.JTextField serialNumJTextField4;
    private javax.swing.JTextField specialityJTextField;
    private javax.swing.JTextField ssnJTextField2;
    private javax.swing.JLabel stateJLbl;
    private javax.swing.JLabel stateJLbl1;
    private javax.swing.JTextField stateJTxtField;
    private javax.swing.JTextField textStatementTxtField;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables


private void displayProduct() {
 
//person    
nameJTextField1.setText(product.getName());
contactNumJTextField6.setText(product.getName());
ageJTextField.setText(product.getAge());
DiseaseNameJTextField10.setText(product.getDiseaseName());
occupationJTextField7.setText(product.getOccupation());
WebsiteUrlJTextField3.setText(product.getWebsiteUrl());
ssnJTextField2.setText(product.getSSN());

//Vehical
modelJTextField1.setText(product.getModel());
colorJTextField.setText(product.getColor());
brandJTextField3.setText(product.getBrand());
serialNumJTextField4.setText(product.getSerialNum());

//Insurance 
insuranceIdTxtField.setText(product.getInsuranceId());
insuranceIdTxtField.setText(product.getPremium());
deductableJTxtField.setText(product.getDeductable());
textStatementTxtField.setText(product.getTextStatement());

//Driver
licenseJTextField1.setText(product.getModel());

//patients

patientJTextField1.setText(product.getPatientId());
lastDateJTextField2.setText(product.getDateOfLastVisit());
nxtAppJTextField3.setText(product.getNextAppointment());
allergyJTextField4.setText(product.getAllergies());
medicationJTextField5.setText(product.getOnMedicine());
contactNumJTextField7.setText(product.getPrimarydoc());

//Address

gpsLocationTxtField.setText(product.getGpsLocation());
cityJTxtField.setText(product.getCity());
stateJTxtField.setText(product.getState());
countryTxtField.setText(product.getCountry());
pincodeTxtField.setText(product.getPinCode());


//Doctor

nameJTextField1.setText(product.getDocName());
branchJTextField.setText(product.getBranch());
numTextField.setText(product.getOfficeContact());
availaibilityJTextField.setText(product.getAvailaibility());
specialityJTextField.setText(product.getSpecility());
docIdTextField3.setText(product.getDocId());
docAddressJTextField2.setText(product.getDocAddress());

    }
}
